'use strict';
const $=(q,scope=document)=>scope.querySelector(q), $$=(q,scope=document)=>[...scope.querySelectorAll(q)];
const stages=[
 {title:'Toda historia tiene<br>un origen.',fields:[['Identidad','ST-0248'],['Material','Granito gris'],['Origen','Lote L-026 · ejemplo'],['Estado','Origen registrado']],event:'Lote de origen asociado'},
 {title:'Cada corte conserva<br>el vínculo.',fields:[['Unidad de origen','ST-0248'],['Piezas derivadas','ST-0248-A / ST-0248-B'],['Retal vinculado','ST-0248-R'],['Estado','Transformación registrada']],event:'Genealogía entre tabla, piezas y retal'},
 {title:'Una ubicación.<br>Un estado conocido.',fields:[['Identidad','ST-0248-A'],['Ubicación','Almacén · A-03'],['Estado','Disponible'],['Fuente','Recepción aceptada']],event:'Entrada confirmada · zona A-03'},
 {title:'La colocación<br>deja evidencia.',fields:[['Identidad','ST-0248-A'],['Ubicación','Fachada norte · F-01'],['Responsable','INS-02 · demostración'],['Estado','Instalación validada']],event:'Ubicación + responsable + evidencia revisada'},
 {title:'Su historia abre<br>nuevas posibilidades.',fields:[['Identidad','ST-0248-A'],['Estado','Recuperada · por evaluar'],['Documentación','Historial conservado'],['Siguiente paso','Comprobar aptitud para el uso']],event:'Recuperación registrada · evaluación pendiente'}
];
let stageIndex=0;
function setStage(i){stageIndex=(i+stages.length)%stages.length;const s=stages[stageIndex];$('#stage-index').textContent=`0${stageIndex+1} / 05`;$('#stage-content').innerHTML=`<h3>${s.title}</h3><dl>${s.fields.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`;$('#stage-event').textContent=s.event;$$('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.stage)===stageIndex)));}
$$('[data-stage]').forEach(b=>b.addEventListener('click',()=>setStage(Number(b.dataset.stage))));$('#next-stage').addEventListener('click',()=>setStage(stageIndex+1));setStage(0);
$('#layer-toggle').addEventListener('click',e=>{const b=e.currentTarget,on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(on));b.lastElementChild.textContent=on?'Capa digital activa':'Activar capa digital';$('.hero').classList.toggle('connected',on);});
$('.menu-toggle').addEventListener('click',e=>{const open=$('.nav').classList.toggle('menu-open');e.currentTarget.setAttribute('aria-expanded',String(open));e.currentTarget.setAttribute('aria-label',open?'Cerrar navegación':'Abrir navegación');});$$('.nav nav a').forEach(a=>a.addEventListener('click',()=>{$('.nav').classList.remove('menu-open');$('.menu-toggle').setAttribute('aria-expanded','false');}));
const objects={
 bench:{id:'B—01',title:'Una pausa. Con memoria.',text:'Banco escultórico de piedra. Su identidad relaciona procedencia, instalación y mantenimiento.',spec:['PIEDRA TALLADA','PATIO CENTRAL'],events:[['D01','Recepción aceptada','Almacén · OP-01'],['D03','Instalación revisada','Patio central · INS-02'],['D180','Revisión registrada','Sin incidencia · MNT-01']]},
 facade:{id:'F—01',title:'Una fachada. Con contexto.',text:'La placa conserva su relación con el lote, el acabado y las evidencias de colocación.',spec:['PLACAS DE PIEDRA','FACHADA NORTE'],events:[['D01','Lote relacionado','Producción · L-026'],['D06','Instalación revisada','Fachada norte · INS-02'],['D90','Inspección registrada','Anclajes por revisar · MNT-01']]},
 stair:{id:'E—01',title:'Un paso. Con recorrido.',text:'Peldaño de granito vinculado a su geometría, documentación de producto y registro de mantenimiento.',spec:['GRANITO GRIS','ESCALERA EXTERIOR'],events:[['D01','Corte registrado','Pieza derivada · ST-0248'],['D04','Instalación revisada','Escalera exterior · INS-02'],['D60','Limpieza registrada','Intervención · MNT-01']]}
};
function setObject(key){const o=objects[key];$('#object-content').innerHTML=`<span class="object-code">${o.id}</span><h3>${o.title}</h3><p>${o.text}</p><div class="object-spec">${o.spec.map(s=>`<span>${s}</span>`).join('')}</div><ol class="event-timeline">${o.events.map(([t,a,d])=>`<li><time>${t}</time><div><strong>${a}</strong><small>${d}</small></div></li>`).join('')}</ol><p class="micro">Historial y elementos de demostración.</p>`;$$('[data-object]').forEach(b=>{const active=b.dataset.object===key;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}
$$('[data-object]').forEach(b=>b.addEventListener('click',()=>setObject(b.dataset.object)));setObject('bench');
const STORAGE_KEY='idstone-explorer-v1';
const blank=()=>({version:1,offline:false,events:[],syncedAt:null,ppeAssigned:false,evidenceFilled:false});
let state=blank(),persistent=true,toastTimer;
try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(raw&&raw.version===1&&Array.isArray(raw.events)){state={...blank(),...raw,events:raw.events.filter(e=>e&&typeof e.id==='string'&&['Recepción','Revisión','Incidencia'].includes(e.type)&&['ST-0248-A','B-01','E-01'].includes(e.piece)&&typeof e.location==='string'&&['pending','accepted'].includes(e.status)&&!isNaN(Date.parse(e.at)))};}}catch{persistent=false;}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch{persistent=false;}$('#storage-status').textContent=persistent?'Los eventos se guardan en este navegador.':'Almacenamiento no disponible: conserva esta pestaña abierta.';if(persistent)$('#storage-status').textContent='Los eventos se guardan en este navegador.';}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
function time(v){return new Date(v).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});}
function offline(){return state.offline||!navigator.onLine;}
function accepted(){return state.events.filter(e=>e.status==='accepted');}
function received(){return [...new Set(accepted().filter(e=>e.type==='Recepción').map(e=>e.piece))];}
function render(){const off=offline(),pending=state.events.filter(e=>e.status==='pending');$('#mode-title').textContent=!navigator.onLine?'Sin conexión de red':state.offline?'Modo offline elegido':'Modo conectado · simulación';$('#mode-led').classList.toggle('offline',off);$('#offline-toggle').setAttribute('aria-pressed',String(state.offline));$('#offline-toggle').innerHTML=state.offline?'Volver a online <span>↗</span>':'Probar sin conexión <span>↗</span>';$('#last-sync').textContent=state.syncedAt?`Última conciliación local: ${time(state.syncedAt)}`:'Sin eventos conciliados todavía';$('#pending-count').textContent=pending.length;$('#accepted-count').textContent=accepted().length;$('#stock-count').textContent=received().length;$('#sync-events').disabled=off||!pending.length;$('#export-events').disabled=!state.events.length;$('#sync-help').textContent=off?'Los datos quedan en este dispositivo. Recupera la conexión para conciliar.':'El envío se inicia cuando tú lo decides. La conciliación está simulada.';$('#event-log').innerHTML=state.events.length?[...state.events].reverse().map(e=>`<div class="log-item"><div><strong>${esc(e.type)} / ${esc(e.piece)}</strong><small>${esc(e.location)} · ${time(e.at)}<br>${esc(e.id)} · OP-01</small></div><span class="log-state ${e.status==='pending'?'pending':''}">${e.status==='pending'?'PENDIENTE':'CONCILIADO'}</span></div>`).join(''):'<div class="empty-log"><span>⌁</span>El siguiente evento lo registras tú.<br><small>Selecciona una operación y una pieza para empezar.</small></div>';$('#ppe-status').textContent=state.ppeAssigned?'Asignado a OP-01 · acuse simulado registrado':'Disponible · pendiente de asignación';$('#ppe-assign').textContent=state.ppeAssigned?'Devolver EPI ↗':'Asignar EPI +';renderEvidence();}
$('#offline-toggle').addEventListener('click',()=>{state.offline=!state.offline;save();render();toast(state.offline?'Modo local activado. Puedes seguir registrando.':'Modo online elegido. La cola espera tu confirmación.');});
$('#capture-event').addEventListener('click',()=>{if(state.events.length>=200){toast('La demo admite 200 eventos. Exporta y reinicia para continuar.');return;}const e={id:'EV-'+(globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)).slice(0,12),type:$('#event-type').value,piece:$('#event-piece').value,location:$('#event-location').value,at:new Date().toISOString(),status:'pending'};state.events.push(e);save();render();toast(offline()?'Evento guardado en este dispositivo.':'Evento capturado. Listo para conciliar.');});
$('#sync-events').addEventListener('click',()=>{if(offline())return;const pending=state.events.filter(e=>e.status==='pending');if(!pending.length)return;pending.forEach(e=>e.status='accepted');state.syncedAt=new Date().toISOString();save();render();toast(`${pending.length} evento${pending.length===1?'':'s'} conciliado${pending.length===1?'':'s'} en la simulación.`);});
window.addEventListener('online',render);window.addEventListener('offline',render);
function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export-events').addEventListener('click',()=>{const cell=v=>'"'+String(v).replace(/"/g,'""')+'"';download('iD-stone-eventos-demo.csv','\uFEFF'+[['id','operacion','unidad','ubicacion','fecha_iso','estado','autor'],...state.events.map(e=>[e.id,e.type,e.piece,e.location,e.at,e.status==='pending'?'pendiente':'conciliado','OP-01'])].map(row=>row.map(cell).join(';')).join('\r\n'),'text/csv;charset=utf-8');toast('Registro de eventos exportado.');});
$$('[data-module]').forEach(b=>b.addEventListener('click',()=>{const name=b.dataset.module;$$('[data-module]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('.module').forEach(el=>el.hidden=el.id!=='module-'+name);}));
function renderEvidence(){const source=state.evidenceFilled?accepted().filter(e=>e.piece==='ST-0248-A').at(-1):null;const fields=source?[['Unidad',source.piece],['Última operación',source.type],['Ubicación',source.location],['Fecha / responsable',time(source.at)+' · OP-01']]:[['Unidad','Pendiente'],['Última operación','Pendiente'],['Ubicación','Pendiente'],['Fecha / responsable','Pendiente']];$('#evidence-progress').textContent=(source?'4':'0')+' / 4 CAMPOS';$('#evidence-fields').innerHTML=fields.map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')+'<div><dt>Ensayo aplicable</dt><dd>Pendiente de aportar</dd></div><div><dt>Aprobación técnica</dt><dd>Pendiente de revisión</dd></div>';}
$('#autofill').addEventListener('click',()=>{state.evidenceFilled=true;save();renderEvidence();toast(accepted().some(e=>e.piece==='ST-0248-A')?'Cuatro campos completados. Ensayo y revisión siguen pendientes.':'Registra y concilia primero un evento de ST-0248-A.');});
$('#ppe-assign').addEventListener('click',()=>{state.ppeAssigned=!state.ppeAssigned;save();render();toast(state.ppeAssigned?'EPI asignado a OP-01 en la demostración.':'Devolución del EPI registrada en la demostración.');});
const dialog=$('#detail-dialog');let previousFocus;
function openDialog(html){previousFocus=document.activeElement;$('#dialog-content').innerHTML=html;dialog.showModal();$('#dialog-close').focus();}
function closeDialog(){dialog.close();previousFocus?.focus();}
$('#dialog-close').addEventListener('click',closeDialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});dialog.addEventListener('close',()=>previousFocus?.focus());
$('#passport-open').addEventListener('click',()=>{const s=stages[stageIndex];openDialog(`<span class="eyebrow">PASAPORTE / DEMOSTRACIÓN</span><h2>La información<br>acompaña a la pieza.</h2><dl>${s.fields.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><h3>Continuidad de identidad</h3><p>RFID y códigos ópticos se relacionan con una identidad persistente. La sustitución de una etiqueta no borra el historial del elemento.</p><h3>Documentos vinculados</h3><p>Ficha de producto, evidencia de instalación y mantenimiento se incorporan según el uso y los permisos. Este pasaporte contiene datos ilustrativos.</p>`);});
$('#delivery-open').addEventListener('click',()=>{const units=received();openDialog(`<span class="eyebrow">ALBARÁN / BORRADOR DE DEMOSTRACIÓN</span><h2>El movimiento<br>escribe el documento.</h2><p>Relación de unidades con recepción conciliada en esta sesión. Cada unidad aparece una vez, aunque tenga varios eventos.</p>${units.length?`<table><thead><tr><th>Unidad</th><th>Cantidad</th><th>Estado</th></tr></thead><tbody>${units.map(u=>`<tr><td>${esc(u)}</td><td>1</td><td>Recibida</td></tr>`).join('')}</tbody></table>`:'<p>No hay recepciones conciliadas. Registra una recepción en Movimientos y pulsa Sincronizar ahora.</p>'}<p>Emisor, receptor, pedido y numeración: pendientes de integración y autorización. No es un albarán válido para operar.</p>${units.length?'<button id="download-delivery" class="button blue">Descargar borrador HTML ↗</button>':''}`);$('#download-delivery')?.addEventListener('click',()=>download('iD-stone-albaran-demo.html','<!doctype html><html lang="es"><meta charset="utf-8"><title>iD.stone · Borrador de albarán</title><style>body{font:16px Arial;max-width:800px;margin:60px auto;padding:25px}table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid #bbb;text-align:left;padding:15px}h1{color:#284fff}</style><h1>iD.stone / Borrador de albarán</h1><p>DEMOSTRACIÓN · NO VÁLIDO PARA OPERAR</p><table><tr><th>Unidad</th><th>Cantidad</th></tr>'+units.map(u=>`<tr><td>${esc(u)}</td><td>1</td></tr>`).join('')+'</table><p>Datos de ejemplo. Emisor, receptor, pedido, numeración y autorización pendientes de integración.</p></html>','text/html;charset=utf-8'));});
$('#reset-demo').addEventListener('click',()=>{openDialog('<h2>Reiniciar el laboratorio.</h2><p>Se borrarán los eventos y las asignaciones de esta demostración guardados en este navegador. Puedes exportar el CSV antes de reiniciar.</p><button id="confirm-reset" class="button blue">Borrar datos de la demo</button>');$('#confirm-reset').addEventListener('click',()=>{state=blank();save();render();closeDialog();toast('Laboratorio reiniciado.');});});
$('#about-open').addEventListener('click',()=>openDialog('<span class="eyebrow">iD.stone / PRODUCT EXPLORER</span><h2>Materia real.<br>Experiencia conceptual.</h2><p>Este prototipo explora identidad, operación y continuidad de la piedra con la arquitectura CUEVA. Las imágenes son conceptos generados con IA y los identificadores, personas e historiales son ficticios.</p><p>Los eventos se guardan en este navegador. El modo offline y la conciliación se demuestran localmente: no existe conexión a servidores CUEVA, ERP ni lectores físicos. No se envían datos ni se utiliza analítica.</p><p>Las capacidades de producto requieren configuración, integración y validación por entorno. La preparación de evidencias no equivale a certificación ISO o UNE.</p>'));
render();save();
if('serviceWorker' in navigator&&/^https?:$/.test(location.protocol)){navigator.serviceWorker.register('./sw.js').catch(()=>{});}
