'use strict';
const hero=document.querySelector('.art-hero');
const layers={matter:['Lo que puedes tocar.<br>Y todo lo que puedes conectar.','OBJETO CONCEPTUAL / TRAVERTINO'],identity:['Una unidad. Una identidad.<br>Un vínculo con su origen.','OBJ—001 / IDENTIDAD ASOCIADA'],memory:['Cada transformación deja historia.<br>Cada vida abre otra posibilidad.','EVENTOS VINCULADOS / DEMOSTRACIÓN']};
document.querySelectorAll('[data-art-layer]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.artLayer;hero.dataset.layer=key;document.querySelectorAll('[data-art-layer]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('#art-layer-copy').innerHTML=layers[key][0];document.querySelector('#orbit-note').textContent=layers[key][1];}));
if(matchMedia('(hover:hover) and (prefers-reduced-motion:no-preference)').matches){hero.addEventListener('pointermove',event=>{const r=hero.getBoundingClientRect();hero.style.setProperty('--mx',((event.clientX-r.left)/r.width-.5)*-14+'px');hero.style.setProperty('--my',((event.clientY-r.top)/r.height-.5)*-9+'px');});hero.addEventListener('pointerleave',()=>{hero.style.setProperty('--mx','0px');hero.style.setProperty('--my','0px');});}
const products={chair:{title:'Arco.',id:'AR—001',material:'Travertino',usage:'Asiento escultórico',image:'assets/chair.webp',description:'Una línea continua, tallada en piedra. La identidad conecta la forma con su procedencia, su instalación y los cuidados que recibe.',event:'Acabado registrado · Taller / OP-01'},basin:{title:'Monolito.',id:'MO—002',material:'Mármol negro',usage:'Lavabo de diseño',image:'assets/basin.webp',description:'Una pieza de presencia mineral. El registro acompaña su transformación, su colocación y la documentación de mantenimiento.',event:'Instalación por revisar · Proyecto / INS-02'}};
document.querySelectorAll('[data-product]').forEach(button=>button.addEventListener('click',()=>{const p=products[button.dataset.product];document.querySelector('#detail-dialog').classList.add('product-modal');openDialog(`<div class="product-dialog"><img src="${p.image}" alt="${p.usage}"><div><span class="eyebrow">COLECCIÓN CONCEPTUAL / ${p.id}</span><h2>${p.title}</h2><p>${p.description}</p><dl><div><dt>Material</dt><dd>${p.material}</dd></div><div><dt>Aplicación</dt><dd>${p.usage}</dd></div><div><dt>Identidad</dt><dd>${p.id}</dd></div><div><dt>Documento</dt><dd>Ficha por completar</dd></div></dl><p class="product-state">${p.event}</p><p>Diseño e historial de ejemplo. La aptitud técnica y los detalles de fabricación requieren validación.</p><button id="product-passport" class="button blue">Explorar el pasaporte ↗</button></div></div>`);document.querySelector('#product-passport').addEventListener('click',()=>{closeDialog();document.querySelector('#pasaporte').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});});}));
document.querySelector('#detail-dialog').addEventListener('close',()=>document.querySelector('#detail-dialog').classList.remove('product-modal'));
let scrollQueued=false;function progress(){const h=document.documentElement;document.documentElement.style.setProperty('--progress',Math.min(100,scrollY/Math.max(1,h.scrollHeight-innerHeight)*100)+'%');scrollQueued=false;}addEventListener('scroll',()=>{if(!scrollQueued){scrollQueued=true;requestAnimationFrame(progress);}},{passive:true});progress();
