(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cinema=$('#cinema-toggle');cinema?.addEventListener('click',()=>{const on=$('#recorrido').classList.toggle('cinematic');cinema.setAttribute('aria-pressed',on);cinema.textContent=on?'Salir del modo cine ↙':'Modo cine ↗';});
const benefits=[
['Origen','Hacer visible el valor del material.','Procedencia, acabados y características dispersos dificultan responder con precisión a un cliente.','Relacionar la unidad con origen, lote, ficha visual y documentación.','Mejor argumento comercial y selección de una pieza concreta. Menos tiempo reconstruyendo su procedencia.','Tiempo para preparar una oferta · fichas completas · consultas resueltas.','Identidad: base operativa CUEVA. Lotes y ficha comercial: adaptación a configurar.','VALOR COMERCIAL','TRACE + EXPERIENCE'],
['Transformación','Proteger el margen en cada corte.','Perder el vínculo entre tabla, piezas y retales impide saber qué material sigue disponible.','Registrar genealogía y destino; conservar dimensiones útiles, foto, acabado y ubicación del retal.','Oportunidad de aprovechar mejor la materia y recuperar material para nuevas ventas.','Rendimiento por tabla · merma · retales localizados y vendidos.','Genealogía: diseñada en el baseline. Mapa de corte y bookmatch: extensiones por desarrollar.','APROVECHAMIENTO','FLOW + LIFE'],
['Almacén','Convertir existencias en disponibilidad.','Buscar piezas, recapturar datos y prometer material que ya está reservado frena la operación comercial.','Conciliar entradas y salidas; distinguir disponible, reservado, bloqueado y en tránsito.','Menor esfuerzo de inventario y preparación; mejor información para comprometer una entrega.','Tiempo de búsqueda · discrepancias · tiempo de preparación de pedido.','Inventario y stock: capacidades parciales. Conciliación e integración WMS: diseñadas, por validar.','PRODUCTIVIDAD','TRACE + FLOW'],
['Entrega','Entregar bien. Resolver antes.','Faltantes, cambios de custodia y documentos dispersos multiplican comprobaciones e incidencias.','Relacionar unidades, expedición y receptor; contrastar la carga y preparar el albarán con datos aceptados.','Oportunidad de reducir rectificaciones y acelerar la revisión documental y la resolución de incidencias.','Errores por expedición · albaranes corregidos · tiempo de cierre de incidencias.','Entrega: piloto CUEVA. Validación de carga y custodia: parciales; albaranes sujetos a integración.','FIABILIDAD','TRACE + VERIFY'],
['Proyecto','Continuar la relación después de vender.','Tras la instalación, cuesta localizar la pieza, su documentación o quién intervino.','Vincular elemento, ubicación, evidencia de instalación e historial de mantenimiento.','Mejor servicio posventa y base para ofrecer mantenimiento documentado y reposición informada.','Tiempo de consulta · incidencias resueltas · intervenciones documentadas.','POI y documentación: alcance a configurar. Integración BIM y servicios de vida útil según proyecto.','SERVICIO','VERIFY + LIFE'],
['Nueva vida','Conservar opciones para el futuro.','Sin dimensiones, estado ni historial es más difícil decidir qué puede recuperarse y volver a utilizarse.','Conservar identidad, material, intervenciones y evaluación de aptitud para el siguiente destino.','Base para reventa y reutilización de unidades aptas, con continuidad documental.','Unidades recuperadas · material reutilizado · tiempo de evaluación.','Circularidad: despliegue por validar. La nueva aplicación exige evaluación técnica de aptitud.','VALOR RESIDUAL','LIFE + EXPERIENCE']
];
function renderBenefit(i){const b=benefits[i],p=$('#benefit-detail');if(!p)return;p.setAttribute('aria-labelledby','benefit-tab-'+i);p.innerHTML=`<div class="benefit-result"><span>${b[7]}</span><h3>${b[1]}</h3><p>${b[4]}</p><div class="benefit-engine">${b[8]}</div></div><div class="benefit-explain"><div><span>LA FRICCIÓN</span><p>${b[2]}</p></div><div><span>LA INTERVENCIÓN</span><p>${b[3]}</p></div><div class="benefit-kpi"><span>CÓMO MEDIRLO</span><p>${b[5]}</p></div><small>${b[6]}</small></div>`;$$('[data-benefit]').forEach((t,j)=>{t.setAttribute('aria-selected',i===j);t.tabIndex=i===j?0:-1;});}
$$('[data-benefit]').forEach((b,i)=>{b.addEventListener('click',()=>renderBenefit(i));b.addEventListener('keydown',e=>{const buttons=$$('[data-benefit]');let n;if(['ArrowRight','ArrowDown'].includes(e.key))n=(i+1)%6;else if(['ArrowLeft','ArrowUp'].includes(e.key))n=(i+5)%6;else if(e.key==='Home')n=0;else if(e.key==='End')n=5;else return;e.preventDefault();buttons[n].focus();renderBenefit(n);});});renderBenefit(0);
const elements=[
 {id:'F—01',name:'Fachada ondulada',family:'FAM—FAC—01',material:'Mármol blanco',params:'Modulación · curvatura · espesor · acabado',context:'Envolvente / posición en el modelo'},
 {id:'E—01',name:'Escalera helicoidal',family:'FAM—ESC—01',material:'Carrara blanco',params:'Radio · huella · contrahuella · acabado',context:'Circulación / tramo del proyecto'},
 {id:'B—01',name:'Banco lazo',family:'FAM—BAN—01',material:'Granito negro',params:'Longitud · sección · apoyo · acabado',context:'Mobiliario / emplazamiento'},
 {id:'L—01',name:'Lavabo escultórico',family:'FAM—LAV—01',material:'Granito Rosa Porriño',params:'Geometría · altura · huecos · acabado',context:'Interior / local del proyecto'}
];let selectedElement=0,bimView='family';
function renderElement(i){selectedElement=i;const e=elements[i],panel=$('#element-record');if(!panel)return;panel.setAttribute('aria-labelledby',bimView==='family'?'bim-family-tab':'bim-unit-tab');
 if(bimView==='family')panel.innerHTML=`<span class="family-code">${e.family} / CONCEPTO</span><div class="element-title"><strong>${e.id}</strong><span>${e.name}</span></div><dl class="family-fields"><div><dt>Material</dt><dd>${e.material}</dd></div><div><dt>Parámetros</dt><dd>${e.params}</dd></div><div><dt>Producto</dt><dd>Identificador de tipo + enlace DPP</dd></div><div><dt>Documentos</dt><dd>Prestaciones, instrucciones y revisión aplicable</dd></div><div><dt>En el modelo</dt><dd>${e.context}</dd></div></dl><small>Plantilla de familia propuesta. Dimensiones, requisitos y documentación técnica pendientes de desarrollo y validación.</small>`;
 else panel.innerHTML=`<span class="family-code">UNIDAD VINCULADA / EJEMPLO</span><div class="element-title"><strong>${e.id}</strong><span>${e.name}</span></div><p>${e.context}</p><ol><li><span>D01 / 09:12</span><b>Recepción</b><small>Almacén · OP-01</small></li><li><span>D03 / 11:40</span><b>Instalación aceptada</b><small>Obra · INS-02</small></li><li><span>D180 / 10:05</span><b>Revisión registrada</b><small>Proyecto · MNT-01</small></li></ol><small>Secuencia simulada. La instancia BIM se relaciona con la unidad; la aceptación exige evidencia y revisión.</small>`;
 $$('[data-element]').forEach((b,j)=>{b.classList.toggle('selected',i===j);b.setAttribute('aria-pressed',i===j);});}
$$('[data-element]').forEach((b,i)=>b.addEventListener('click',()=>renderElement(i)));
function changeBIM(view){bimView=view;$$('[data-bim-view]').forEach(b=>{const selected=b.dataset.bimView===view;b.setAttribute('aria-selected',selected);b.tabIndex=selected?0:-1;});renderElement(selectedElement);}
$$('[data-bim-view]').forEach((b,i)=>{b.addEventListener('click',()=>changeBIM(b.dataset.bimView));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const bs=$$('[data-bim-view]'),next=e.key==='Home'?0:e.key==='End'?1:1-i;bs[next].focus();changeBIM(bs[next].dataset.bimView);});});renderElement(0);
})();
