(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const hero=$('#lectura-automatica'),read=$('#read-stone'),tag=$('#tag-inspect'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let busy=false;
function log(i,title,desc){const row=document.createElement('li');row.className='flash';row.innerHTML=`<span>0${i}</span><b>${title}</b><small>${desc}</small>`;$('#readout-log').append(row);}
function readStone(){if(busy)return;busy=true;read.disabled=true;tag.disabled=true;hero.classList.add('reading');$('#reader-indicator').textContent='CAPTURANDO · DEMO';$('#readout-log').innerHTML='';log(1,'Paso detectado.','3 identificadores de ejemplo en el puesto A—01.');setTimeout(()=>{log(2,'Contexto aplicado.','Neurona CUEVA · duplicados filtrados · recepción.');$('#reader-indicator').textContent='PROCESANDO · DEMO';},reduced.matches?0:650);setTimeout(()=>{log(3,'Evento propuesto.','Recepción pendiente. El stock aún no cambia.');$('#reader-indicator').textContent='PENDIENTE · DEMO';hero.classList.remove('reading');read.disabled=false;tag.disabled=false;read.innerHTML='Repetir el paso <span>↻</span>';busy=false;},reduced.matches?10:1500);}
read.addEventListener('click',readStone);tag.addEventListener('click',readStone);
const stations={
recepcion:{code:'A—01 / ENTRADA',title:'Recibir con contexto.',text:'El paso de material identificado propone una recepción. El sistema contrasta las unidades con lo esperado antes de incorporar el movimiento.',values:['Identificadores detectados','Puesto + recepción prevista','Recepción por conciliar']},
produccion:{code:'P—02 / TRANSFORMACIÓN',title:'Conservar el vínculo.',text:'Un puesto de lectura asocia la unidad a la operación. El resultado del corte y las nuevas identidades se confirman para mantener la genealogía.',values:['Tabla identificada','Orden + estación de trabajo','Operación por validar']},
expedicion:{code:'E—03 / SALIDA',title:'Comprobar antes de salir.',text:'Las lecturas se contrastan con las unidades previstas en la expedición. Faltantes y diferencias pasan a revisión; el albarán parte de los datos aceptados.',values:['Unidades en el punto de salida','Pedido + carga prevista','Expedición por conciliar']}};
function station(key){const s=stations[key];$('#station-panel').setAttribute('aria-labelledby','station-'+key);$('#station-panel').innerHTML=`<span class="station-code">${s.code}</span><h4>${s.title}</h4><p>${s.text}</p><dl>${['CAPTURA','CONTEXTO','SALIDA'].map((l,i)=>`<div><dt>${l}</dt><dd>${s.values[i]}</dd></div>`).join('')}</dl>`;$$('[data-station]').forEach(b=>{const sel=b.dataset.station===key;b.setAttribute('aria-selected',sel);b.tabIndex=sel?0:-1;});}
$$('[data-station]').forEach((b,i)=>{b.addEventListener('click',()=>station(b.dataset.station));b.addEventListener('keydown',e=>{const bs=$$('[data-station]');let n;if(e.key==='ArrowRight')n=(i+1)%3;else if(e.key==='ArrowLeft')n=(i+2)%3;else if(e.key==='Home')n=0;else if(e.key==='End')n=2;else return;e.preventDefault();bs[n].focus();station(bs[n].dataset.station);});});station('recepcion');
const menu=$('#mobile-menu'),toggle=$('#mobile-menu-button');function closeMenu(){menu.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Abrir menú');toggle.textContent='☰';}toggle.addEventListener('click',()=>{const open=menu.hidden;menu.hidden=!open;toggle.setAttribute('aria-expanded',open);toggle.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');toggle.textContent=open?'×':'☰';});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){closeMenu();toggle.focus();}});window.addEventListener('resize',()=>{if(innerWidth>760)closeMenu();});
})();
